# Generated by Django 2.1.7 on 2019-03-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_calc', '0002_auto_20190303_0434'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Expenceses',
            new_name='Expences',
        ),
    ]
