# Generated by Django 2.1.7 on 2019-03-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_calc', '0003_auto_20190303_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('cost', models.IntegerField(blank=True, default=None, null=True)),
                ('photo_url', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('r1_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r1_price_range', models.IntegerField(blank=True, default=None, null=True)),
                ('r1_latitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r1_longitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r1_photos_url', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('r1_user_rating', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=1, null=True)),
                ('r1_cuisines', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('r1_has_online_delivery', models.IntegerField(blank=True, default=None, null=True)),
                ('r2_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r2_price_range', models.IntegerField(blank=True, default=None, null=True)),
                ('r2_latitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r2_longitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r2_photos_url', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('r2_user_rating', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=1, null=True)),
                ('r2_cuisines', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('r2_has_online_delivery', models.IntegerField(blank=True, default=None, null=True)),
                ('r3_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r3_price_range', models.IntegerField(blank=True, default=None, null=True)),
                ('r3_latitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r3_longitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r3_photos_url', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('r3_user_rating', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=1, null=True)),
                ('r3_cuisines', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('r3_has_online_delivery', models.IntegerField(blank=True, default=None, null=True)),
                ('r4_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r4_price_range', models.IntegerField(blank=True, default=None, null=True)),
                ('r4_latitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r4_longitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('r4_photos_url', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('r4_user_rating', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=1, null=True)),
                ('r4_cuisines', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('r4_has_online_delivery', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('price_range', models.IntegerField(blank=True, default=None, null=True)),
                ('latitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('photos_url', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=1, null=True)),
                ('cuisines', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('has_online_delivery', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
