# Generated by Django 2.1.7 on 2019-03-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_calc', '0004_neighborhoods_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhoods',
            name='r1_user_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhoods',
            name='r2_user_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhoods',
            name='r3_user_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='neighborhoods',
            name='r4_user_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='user_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=10, null=True),
        ),
    ]
